type StatusCodeType = {
  BAD_REQUEST: number
  UNAUTHORIZED: number
  PAYMENT_REQUIRED: number
  FORBIDDEN: number
  NOT_FOUND: number
  METHOD_NOT_ALLOWED: number
  NOT_ACCEPTABLE: number
  PROXY_AUTHENTICATION_REQUIRED: number
  REQUEST_TIMEOUT: number
  CONFLICT: number
  GONE: number
  LENGTH_REQUIRED: number
  INTERNAL_SERVER_ERROR: number
  UNPROCESSABLE_ENTITY: number
  OK: number
}
export const StatusCode: StatusCodeType = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  PAYMENT_REQUIRED: 402,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  NOT_ACCEPTABLE: 406,
  PROXY_AUTHENTICATION_REQUIRED: 407,
  REQUEST_TIMEOUT: 408,
  CONFLICT: 409,
  GONE: 410,
  LENGTH_REQUIRED: 411,
  UNPROCESSABLE_ENTITY: 422,
  INTERNAL_SERVER_ERROR: 500,
  OK: 200,
} as const
